name: "Actions Test"

on:  
  workflow_dispatch: # manual

jobs:
  name-of-job:
    runs-on: windows-latest
    steps:
      - name: Hello world
        run: 
          write-output "Hello World"
      - name: Display the environment variables and their values
        run: 
          print %ENV
        shell: perl {0}
